set-option -g default-terminal 'tmux-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'
set -g default-terminal "${TERM}"

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

set -g mouse on
set -g base-index 1             # Start indexing winodws at 1 instead of 0
setw -g pane-base-index 1       # Start pane indexing at 1 
set -g renumber-windows on      # Renumber windows on close
setw -g mode-keys vi            # Set Vi key bindings
set -g set-clipboard on          # use system clipboard


set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
set -g @fzf-url-history-limit '1000'

# Some basic catpuccin mocha colors.
set -g @ctp_bg "#24273a"
set -g @ctp_surface_1 "#494d64"
set -g @ctp_fg "#cad3f5"
set -g @ctp_mauve "#c6a0f6"
set -g @ctp_crust "#181926"

# Make the status line pretty and add some modules
set -g status-position top
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

# status line
set -gF status-style "bg=#{@ctp_bg},fg=#{@ctp_fg}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'wfxr/tmux-fzf-url'

#Configure catppuccin
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"
# Set pane border styles
set -g @catppuccin_pane_border_style "fg=gray"
set -g @catppuccin_pane_active_border_style "fg=blue" 
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W#{?window_zoomed_flag,(),}"
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g pane-active-border-style 'fg=blue,bg=default'
set -g pane-border-lines single
# Update the status bar every second to keep names in sync
set-option -g status-interval 1
# Set the window name to the base name of the current path
set-option -g automatic-rename-format "#{?#{==:#{pane_current_command},zsh},#{b:pane_current_path},#{pane_current_command}}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
