alias pro="cd ~/Sites; ls -lah"
alias initjspro="touch package.json index.html webpack.config.js src/app.js"
alias progo="cd ~/Sites; cd $1"
alias nzta="cd ~/Sites/nzta1"
alias ss="cd ~/SS; ls -lah"
alias tsp="cd ~/tsp; ls -lah"
alias dashcd="tsp; cd dash; ls -lah"
alias brewhome="cd /usr/local/Cellar/"
alias indexsolr="sake dev/tasks/Solr_Configure; sake dev/tasks/Solr_Reindex"
alias devbuild="sake dev/build 'flush=1'"
alias xdebugOn="export XDEBUG_CONFIG='idekey=xdebug'; "
alias xdebugOff="unset XDEBUG_CONFIG; "
